version: 2
updates:
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nix"
    directory: "/templates/python-uv/nix"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nix"
    directory: "/templates/python-uv-office/nix"
    schedule:
      interval: "monthly"

  - package-ecosystem: "nix"
    directory: "/templates/node/nix"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

